name: nginx
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build dockerfile
        run: docker build -t docker-practice:1.0 .

      - name: verify docker images
        run: docker images
  
  
    
